language: php
php:
  - 7.2
  - 5.5
before_install:
  - export PATH="$PATH:$(composer global config bin-dir --absolute)"
  - composer global require "squizlabs/php_codesniffer=3.*"
  - phpenv rehash
script:
  - phpcs -p -v --extensions=php --standard="`pwd`/WCF" "`pwd`/src"
