version: 2.1

jobs:
  syntax:
    docker:
      - image: php:7.2
    steps:
      - checkout
      - run:
          name: Install CodeSniffer
          command: pear install pear/PHP_CodeSniffer
      - run:
          name: Check Syntax
          command: phpcs -p -v --extensions=php --standard="`pwd`/WCF" "`pwd`/src"

workflows:
  version: 2
  syntax:
    jobs:
      - syntax:
          filters:
            branches:
              only: [ master, develop ]